In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<font size="5" color="black">Quiz</font>

<p>독립변수 X : 지역명 2, 연도, 월</p>
- 지역명 2 : 지역명 필드를 라벨 인코딩하여 추가

<p>종속변수 Y : 평당분양가격</p>

- 독립변수와 종속변수의 스케일 조정
    * 정규화 작업 후 : 지역명2m, 연도m, 월m 컬럼으로 추가 (df_m)
    * 표준화 작업 후 : 지역명2s, 연도s, 월s 컬럼으로 추가 (df_s)

In [7]:
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Input
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

In [136]:
data = pd.read_csv('https://raw.githubusercontent.com/4aix/data/refs/heads/master/ch13_apt_fillna_median.csv')
df = pd.DataFrame(data)

# 지역명 라벨 인코딩

In [19]:
df.get('지역명')

0       서울
1       부산
2       대구
3       인천
4       광주
        ..
2171    전북
2172    전남
2173    경북
2174    경남
2175    제주
Name: 지역명, Length: 2176, dtype: object

In [137]:
labeled_data = LabelEncoder().fit_transform(df.get('지역명'))

In [138]:
df['지역명2'] = labeled_data

In [139]:
df

     지역명   평당분양가격    연도   월  지역명2
0     서울  18189.0  2013  12     8
1     부산   8111.0  2013  12     7
2     대구   8080.0  2013  12     5
3     인천  10204.0  2013  12    11
4     광주   6098.0  2013  12     4
...   ..      ...   ...  ..   ...
2171  전북  12058.2  2024   8    13
2172  전남  13120.8  2024   8    12
2173  경북  13827.0  2024   8     3
2174  경남  13252.8  2024   8     2
2175  제주  25419.9  2024   8    14

[2176 rows x 5 columns]

# MinMaxScaling

In [147]:
X_data = df[['지역명2', '연도','월']]
y_data = df[['평당분양가격']]
scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

norm_scaled_X = scaler_X.fit_transform(X_data)
norm_scaled_y = scaler_y.fit_transform(y_data)

In [148]:
df_m = pd.DataFrame(norm_scaled_X, columns=['지역명2m', '연도m', '월m'])
df_m['평당분양가격m'] = norm_scaled_y

In [149]:
df_m

       지역명2m  연도m        월m   평당분양가격m
0     0.5000  0.0  1.000000  0.328198
1     0.4375  0.0  1.000000  0.065274
2     0.3125  0.0  1.000000  0.064466
3     0.6875  0.0  1.000000  0.119878
4     0.2500  0.0  1.000000  0.012757
...      ...  ...       ...       ...
2171  0.8125  1.0  0.636364  0.168252
2172  0.7500  1.0  0.636364  0.195974
2173  0.1875  1.0  0.636364  0.214398
2174  0.1250  1.0  0.636364  0.199418
2175  0.8750  1.0  0.636364  0.516844

[2176 rows x 4 columns]

# StandardScaling

In [150]:
X_data = df[['지역명2', '연도','월']]
y_data = df[['평당분양가격']]
scaler_X = StandardScaler()
scaler_y = StandardScaler()

std_scaled_X = scaler_X.fit_transform(X_data)
std_scaled_y = scaler_y.fit_transform(y_data)

df_s = pd.DataFrame(std_scaled_X, columns=['지역명2s', '연도s', '월s'])
df_s['평당분양가격s'] = std_scaled_y

In [151]:
df_s

         지역명2s       연도s       월s   평당분양가격s
0     0.000000 -1.875367  1.62196  1.168591
1    -0.204124 -1.875367  1.62196 -0.728312
2    -0.612372 -1.875367  1.62196 -0.734147
3     0.612372 -1.875367  1.62196 -0.334363
4    -0.816497 -1.875367  1.62196 -1.107203
...        ...       ...      ...       ...
2171  1.020621  1.664199  0.46374  0.014639
2172  0.816497  1.664199  0.46374  0.214643
2173 -1.020621  1.664199  0.46374  0.347566
2174 -1.224745  1.664199  0.46374  0.239489
2175  1.224745  1.664199  0.46374  2.529607

[2176 rows x 4 columns]

# 지역명 원-핫 인코딩

In [53]:
onehot_encoding_data = to_categorical(labeled_data)

In [63]:
onehot_encoding_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], dtype=float32)